### ISSUE TITLE
Jenkins job fails with multiple scripts in Selenium builder suite

### ISSUE THREAD

**Issue by nortoncn** [saucelabs/ci-sauce#11]
Hi,
I hope i have posted this in the right place, apologies if not.
We have a Jenkins system using Sauce Labs and Selenium Builder plugins.
If we run a suite with a single test script, it runs fine. As soon as we add multiple test scripts to the suite, the build fails. Console output is below. Any ideas? Is it possible to get a build with more logging?

Starting to run selenium builder command
Starting test run.
Initialising driver.
SauceOnDemandSessionID=228feeff45414838b3d26d6c30f1f2d7 job-name=null
Running step 1:Step step.
Running step 2:Step step.
Running step 3:Step step.
Running step 4:Step step.
Running step 5:Step step.
Quitting driver.
Starting test run.
Initialising driver.
Error running selenium builder command
Build step 'Invoke Selenium Builder script' marked build as failure
Finished: FAILURE

Our suite is as follows:

{
  "type": "suite",
  "seleniumVersion": "2",
  "formatVersion": 1,
  "scripts": [
    {
      "where": "github",
      "path": "GoogleTestScript.json"
    },
	{
      "where": "github",
      "path": "GoogleTestScript2.json"
    }
  ],
  "shareState": true
}

Many thanks for your help,
Chris

**Comment by rossrowe** [comment]
Thanks for letting me know, I'll try replicate the issue and I'll let you
know when I've got a fix ready.  Would you mind checking the Jenkins system
log (via Manage Jenkins -System Log - All System Logs) to see if a specific
exception was logged?

**Comment by nortoncn** [comment]
Thanks for your swift reply! Didn’t think of that.

Our log is:

Apr 16, 2015 8:16:55 AM WARNING com.saucelabs.ci.SeleniumBuilderManager executeSeleniumBuilder

Error running selenium builder command
java.lang.RuntimeException: Test run failed: unable to create driver.
                at com.sebuilder.interpreter.TestRun.initRemoteWebDriver(TestRun.java:242)
                at com.sebuilder.interpreter.TestRun.next(TestRun.java:124)
                at com.sebuilder.interpreter.TestRun.finish(TestRun.java:171)
                at com.sebuilder.interpreter.Script.run(Script.java:103)
                at com.saucelabs.ci.SeleniumBuilderManager.executeSeleniumBuilder(SeleniumBuilderManager.java:94)
                at hudson.plugins.selenium_builder.SeleniumBuilderBuilder$SeleniumBuilderInvoker.call(SeleniumBuilderBuilder.java:95)
                at hudson.plugins.selenium_builder.SeleniumBuilderBuilder$SeleniumBuilderInvoker.call(SeleniumBuilderBuilder.java:80)
                at hudson.remoting.LocalChannel.call(LocalChannel.java:45)
                at hudson.plugins.selenium_builder.SeleniumBuilderBuilder.perform(SeleniumBuilderBuilder.java:51)
                at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:20)
                at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:770)
                at hudson.model.Build$BuildExecution.build(Build.java:199)
                at hudson.model.Build$BuildExecution.doRun(Build.java:160)
                at hudson.model.AbstractBuild$AbstractBuildExecution.run(AbstractBuild.java:533)
                at hudson.model.Run.execute(Run.java:1759)
                at hudson.matrix.MatrixRun.run(MatrixRun.java:146)
                at hudson.model.ResourceController.execute(ResourceController.java:89)
                at hudson.model.Executor.run(Executor.java:240)
Caused by: org.openqa.selenium.UnsupportedCommandException: No browserName or device specified in session request. Please check our platforms documentation (https://saucelabs.com/docs/platforms): {'platform': None, 'browserName': None, 'name': None}
Command duration or timeout: 154 milliseconds
Build info: version: '2.35.0', revision: '8df0c6bedf70ff9f22c647788f9fe9c8d22210e2', time: '2013-08-17 12:46:41'
System info: os.name: 'Linux', os.arch: 'amd64', os.version: '3.14.35-28.38.amzn1.x86_64', java.version: '1.8.0_40'
Driver info: org.openqa.selenium.remote.RemoteWebDriver
                at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
                at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
                at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
                at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
                at org.openqa.selenium.remote.ErrorHandler.createThrowable(ErrorHandler.java:191)
                at org.openqa.selenium.remote.ErrorHandler.throwIfResponseFailed(ErrorHandler.java:145)
                at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:554)
                at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:216)
                at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:111)
                at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:129)
                at com.saucelabs.ci.SeleniumBuilderManager$SauceRemoteDriver.make(SeleniumBuilderManager.java:279)
                at com.sebuilder.interpreter.TestRun.initRemoteWebDriver(TestRun.java:234)
                ... 17 more

**Comment by nortoncn** [comment]
Wow, thanks so much for the fast response.
Could you please advise how I can actually get the fix? Do we need to wait for a release?
Thanks,
Chris

**Comment by rossrowe** [comment]
Hi, I've released version v1.12 of the plugin which should fix the issue.
It should be available in the Jenkins plugin repository within the next few
hours, please let me know how it goes.

**Comment by nortoncn** [comment]
Hi Ross,
Thanks for that.
The plugin installed successfully and we are further forward but unfortunately there still seems to be an issue with running a suite.

Here is a suite example:

{
  "type": "suite",
  "seleniumVersion": "2",
  "formatVersion": 1,
  "scripts": [
    {
      "where": "github",
      "path": "Google1.json"
    },
    {
      "where": "github",
      "path": "Google2.json"
    }
  ],
  "shareState": true
}

When running on Sauce Labs, we expected it to fire up one VM and run the tests sequentially (like running tests from Selenium Builder directly to Sauce labs).  Instead, it fires up 2 VMs (one for each test) and they then fail.

Can you confirm if this is because the shareState flag is being ignored or could this be a setting we have not configured correctly?

Many thanks,
Chris

**Comment by rossrowe** [comment]
Yep, the plugin was creating a new RemoteWebDriver instance for each script...I've just released version 1.13 of the plugin, can you try this version out and let me know how it goes?

**Comment by nortoncn** [comment]
Thanks Ross. I’m just waiting for it to appear in Jenkins Updates then I will test straight away

Chris

**Comment by nortoncn** [comment]
Thanks so much Ross, the suite now runs one test after another and we have big grins ☺

We have one last thing; if we run the suite on more than one platform/browser in Sauce Labs, they run sequentially as opposed to parallel. We have 25 parallel tests available so would like to take advantage of this.

Thanks again,

Chris

**Comment by rossrowe** [comment]
Hi, including support for parallel testing will be a bit more time consuming, as I'll need to include some changes to the UI to support enabling and configuring of parallel testing...I'll take a look into this and I'll let you know when I've got a new version ready

**Comment by nortoncn** [comment]
Once again Ross, your support is very much appreciated.

I’m not sure whether this will make a difference but we are currently using a ‘Multi-Configuration’ Jenkins job which gives you a UI with a check box per platform/browser (as below). This gives a build per platform/browser.

[cid:image001.png@01D07E7F.DC6AD680]

If you use a ‘Freestyle’ Jenkins job you only get the options below. However this currently does not seem to work with the Selenium Builder plugin if you select more than one platform/browser.

[cid:image002.png@01D07E7F.DC6AD680]


The reason I mention this is that I’m not sure whether what you will propose will work with, or independently of these UI’s.

Many thanks,
Chris

**Comment by rossrowe** [comment]
Sorry for the delay, I've just released version 1.14 of the plugin which includes support for parallel builds, and will also handle multiple selected browsers, when you get a chance can you try this version out?

**Comment by nortoncn** [comment]
Hey Ross,
Awesome thanks. We have to move to another Jenkins system so as soon as that is working, we will test your fix and give feedback.

Thanks again
Chris
