### ISSUE TITLE
The latest SC version can't be downloaded

### ISSUE THREAD

**Issue by valfirst** [saucelabs/ci-sauce#306]
## Expected Behavior
The latest SC version can be downloaded successfully.

## Actual Behavior

An attempt to download SC using URL built by library: 
https://api.us-west-1.saucelabs.com/rest/v1/public/tunnels/sauce-connect/download?arch=x86_64&os=macos

results in HTTP response: `404: Not Found`.

And then error is thrown:
```java
Caused by: org.json.JSONException: A JSONObject text must begin with '{' at 1 [character 2 line 1]
        at org.json.JSONTokener.syntaxError(JSONTokener.java:503) ~[json-20240303.jar:?]
        at org.json.JSONObject.<init>(JSONObject.java:213) ~[json-20240303.jar:?]
        at org.json.JSONObject.<init>(JSONObject.java:430) ~[json-20240303.jar:?]
        at com.saucelabs.ci.sauceconnect.SauceConnectManager.getLatestSauceConnectVersion(SauceConnectManager.java:334) ~[ci-sauce-2.1.jar:2.1]
        at org.apache.commons.lang3.concurrent.AbstractConcurrentInitializer.initialize(AbstractConcurrentInitializer.java:179) ~[commons-lang3-3.17.0.jar:3.17.0]
        at org.apache.commons.lang3.concurrent.LazyInitializer.get(LazyInitializer.java:151) ~[commons-lang3-3.17.0.jar:3.17.0]
        at com.saucelabs.ci.sauceconnect.SauceConnectManager.getVersion(SauceConnectManager.java:439) ~[ci-sauce-2.1.jar:2.1]
        at com.saucelabs.ci.sauceconnect.SauceConnectManager$OperatingSystem.getDirectory(SauceConnectManager.java:122) ~[ci-sauce-2.1.jar:2.1]
        at com.saucelabs.ci.sauceconnect.SauceConnectManager.getUnzipDir(SauceConnectManager.java:412) ~[ci-sauce-2.1.jar:2.1]
        at com.saucelabs.ci.sauceconnect.SauceConnectManager.prepAndCreateProcess(SauceConnectManager.java:231) ~[ci-sauce-2.1.jar:2.1]
        at com.saucelabs.ci.sauceconnect.AbstractSauceTunnelManager.openConnection(AbstractSauceTunnelManager.java:534) ~[ci-sauce-2.1.jar:2.1]
        at com.saucelabs.ci.sauceconnect.AbstractSauceTunnelManager.openConnection(AbstractSauceTunnelManager.java:446) ~[ci-sauce-2.1.jar:2.1]
```

## Steps to Reproduce the Problem

Enable downloading of the latest SC.

## Specifications

  - Version: ci-sauce:2.1
  - Platform: MacOS
  - Subsystem:

**Comment by alexh-sauce** [comment]
Thanks for the report. Looking into this now.

**Comment by alexh-sauce** [comment]
Looks like I jumped the gun on releasing before the REST API changes were available. It should be working now.

**Comment by valfirst** [comment]
Thanks, the issue is resolved
